# Generated by Django 6.0 on 2025-12-20 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=25)),
                ('tx_ref', models.CharField(help_text='Our internal reference sent to provider', max_length=100, unique=True)),
                ('provider_ref', models.CharField(blank=True, help_text='Reference from Chapa', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Created', 'CREATED'), ('Pending', 'PENDING'), ('Success', 'SUCCESS'), ('Failed', 'FAILED'), ('Refunded', 'REFUNDED')], default='Created', max_length=50)),
                ('response_dump', models.JSONField(blank=True, default=dict)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
