spring.application.name=inventory-service

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmacy_inventory
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
# update: automatically creates/updates tables based on your Java classes
spring.jpa.hibernate.ddl-auto=update
# show-sql: prints SQL queries to console (good for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect