# Generated by Django 6.0 on 2025-12-12 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_pharmacy',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('pharmacy', 'Pharmacy'), ('pharmacy_admin', 'Pharmacy Admin')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role__in': ['pharmacy', 'pharmacy_admin']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
